name: .NET Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore HugeImages.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release HugeImages.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release HugeImages.sln
